export const PREPARE_BATTLE = "PREPARE_BATTLE";
export const FETCH_SAFE_CHALLENGES = "FETCH_SAFE_CHALLENGES";
export const CREATE_CHALLENGE = "CREATE_CHALLENGE";
export const CREATE_POST = "CREATE_POST";
export const FETCH_CHALLENGES = "FETCH_CHALLENGES";
export const FETCH_USER = "FETCH_USER";
export const SAVE_SUCCESS = "SAVE_SUCCESS";
